### PR TITLE
217 frontend css fix friend highscore

### PR DESCRIPTION
**Pull request by xCandyFun**
The mobile adaption is looking good for me but maybe not for you. The only ones left are the picture for the user both on desktop and mobile.

### CODE REVIEW

**Review by signealfonson — CHANGES_REQUESTED** [review]
Remove friends and try to place Friends highscore there instead. Translate it to swedish. Move the scroll menu inside the friends highscore div.
Remove the binding in Geografikäck and try to make it to stay in one row while flexing. 
Try to put the shorts-info div inside the bigger div with about me.
Try to put a margin on friends highscore since it ends outside the screen right now.
Try to put an image inside the profile picture, use one of the avatar pictures.

**Review by signealfonson — CHANGES_REQUESTED** [review]
Ändra "vänner highscore" till "Vänners highscore" samt centrera den, kanske lägga någon bakgrund bakom?
Lägg scrollmenyn under, centrerad och gör den lite större.
Se till att highscoreresultaten ser likadana ut och döp om dem i scrollmenyn.
Gör boxen med highscoreresultat storleksanpassad till hur många vänner man har.
Flexa snabbinfon i mobilläge så den passar storleken och resterande.
Ta bort ytan för profilbilden helt.
Se till att spårvagnarna samt bakgrundsdiven bakom spårvagnarna följer med i storleksanpassning.

**Comment by xCandyFun** [comment]
I did try do make that the highscorelist adjust the size accordingly to how many friends there are. The problem is that the background border moves up and down so that the scroll menu button change place.

**Review by williamDenStore — CHANGES_REQUESTED** [review]
the about me page is of set from the box above when at 450px width

username is missing

background image is too far at the bottom. for some reason I can scroll really far down. despite it not being anything there

friend highscore should adapt its height depending on how many elements are in it so it isn't a half empty box.

on my large screen everything is too small. On my smaller laptop screen everything is to large. Use % instead of rem hardcoded for you screen size. that will help with mobile adaptability. and make is usable for more screen sizes

**Review by williamDenStore — APPROVED** [review]
perfect. username doesn't quite fit in the bubble though

**Pull request merged**
